[[redirects]]
  from = 'https://laughing-haibt-230e7b.netlify.com/*'
  to = 'https://tomstew.art/:splat'
  status = 301
  force = true

[[headers]]
  for = '/*'
  [headers.values]
    Strict-Transport-Security = 'max-age=63072000; includeSubDomains; preload'